language: node_js
sudo: 'false'
before_script:
- npm install -g polymer-cli
- polymer install --variants
node_js: '9'
addons:
  firefox: latest
  chrome: stable
script:
- xvfb-run polymer test
dist: trusty
cache:
  directories:
  - node_modules
  - bower_components
